const countryData = {
  AED: { flagCode: "AE", currencyName: "UAE Dirham", countryName: "United Arab Emirates" },
  AFN: { flagCode: "AF", currencyName: "Afghan Afghani", countryName: "Afghanistan" },
  XCD: { flagCode: "AG", currencyName: "East Caribbean Dollar", countryName: "Antigua and Barbuda" },
  ALL: { flagCode: "AL", currencyName: "Albanian Lek", countryName: "Albania" },
  AMD: { flagCode: "AM", currencyName: "Armenian Dram", countryName: "Armenia" },
  ANG: { flagCode: "AN", currencyName: "Netherlands Antillian Guilder", countryName: "Netherlands Antilles" },
  AOA: { flagCode: "AO", currencyName: "Angolan Kwanza", countryName: "Angola" },
  AQD: { flagCode: "AQ", currencyName: "Antarctican dollar", countryName: "Antarctica" },
  ARS: { flagCode: "AR", currencyName: "Argentine Peso", countryName: "Argentina" },
  AUD: { flagCode: "AU", currencyName: "Australian Dollar", countryName: "Australia" },
  AZN: { flagCode: "AZ", currencyName: "Azerbaijani Manat", countryName: "Azerbaijan" },
  BAM: { flagCode: "BA", currencyName: "Bosnia and Herzegovina Mark", countryName: "Bosnia and Herzegovina" },
  BBD: { flagCode: "BB", currencyName: "Barbados Dollar", countryName: "Barbados" },
  BDT: { flagCode: "BD", currencyName: "Bangladeshi Taka", countryName: "Bangladesh" },
  XOF: { flagCode: "BE", currencyName: "West African CFA franc", countryName: "Benin" },
  BGN: { flagCode: "BG", currencyName: "Bulgarian Lev", countryName: "Bulgaria" },
  BHD: { flagCode: "BH", currencyName: "Bahraini Dinar", countryName: "Bahrain" },
  BIF: { flagCode: "BI", currencyName: "Burundian Franc", countryName: "Burundi" },
  BMD: { flagCode: "BM", currencyName: "Bermudian Dollar", countryName: "Bermuda" },
  BND: { flagCode: "BN", currencyName: "Brunei Dollar", countryName: "Brunei" },
  BOB: { flagCode: "BO", currencyName: "Bolivian Boliviano", countryName: "Bolivia" },
  BRL: { flagCode: "BR", currencyName: "Brazilian Real", countryName: "Brazil" },
  BSD: { flagCode: "BS", currencyName: "Bahamian Dollar", countryName: "Bahamas" },
  NOK: { flagCode: "BV", currencyName: "Norwegian Krone", countryName: "Bouvet Island" },
  BWP: { flagCode: "BW", currencyName: "Botswana Pula", countryName: "Botswana" },
  BYR: { flagCode: "BY", currencyName: "Belarusian Ruble", countryName: "Belarus" },
  BZD: { flagCode: "BZ", currencyName: "Belize Dollar", countryName: "Belize" },
  CAD: { flagCode: "CA", currencyName: "Canadian Dollar", countryName: "Canada" },
  CDF: { flagCode: "CD", currencyName: "Congolese Franc", countryName: "Democratic Republic of the Congo" },
  XAF: { flagCode: "CF", currencyName: "Central African CFA Franc", countryName: "Central African Republic" },
  CHF: { flagCode: "CH", currencyName: "Swiss Franc", countryName: "Switzerland" },
  CLP: { flagCode: "CL", currencyName: "Chilean Peso", countryName: "Chile" },
  CNY: { flagCode: "CN", currencyName: "Chinese Renminbi", countryName: "China" },
  COP: { flagCode: "CO", currencyName: "Colombian Peso", countryName: "Colombia" },
  CRC: { flagCode: "CR", currencyName: "Costa Rican Colon", countryName: "Costa Rica" },
  CUP: { flagCode: "CU", currencyName: "Cuban Peso", countryName: "Cuba" },
  CVE: { flagCode: "CV", currencyName: "Cape Verdean Escudo", countryName: "Cape Verde" },
  CYP: { flagCode: "CY", currencyName: "Cypriot Pound", countryName: "Cyprus" },
  CZK: { flagCode: "CZ", currencyName: "Czech Koruna", countryName: "Czech Republic" },
  DJF: { flagCode: "DJ", currencyName: "Djiboutian Franc", countryName: "Djibouti" },
  DKK: { flagCode: "DK", currencyName: "Danish Krone", countryName: "Denmark" },
  DOP: { flagCode: "DO", currencyName: "Dominican Peso", countryName: "Dominican Republic" },
  DZD: { flagCode: "DZ", currencyName: "Algerian Dinar", countryName: "Algeria" },
  ECS: { flagCode: "EC", currencyName: "Ecuadorian Sucre", countryName: "Ecuador" },
  EEK: { flagCode: "EE", currencyName: "Estonian Kroon", countryName: "Estonia" },
  EGP: { flagCode: "EG", currencyName: "Egyptian Pound", countryName: "Egypt" },
  ETB: { flagCode: "ET", currencyName: "Ethiopian Birr", countryName: "Ethiopia" },
  EUR: { flagCode: "FR", currencyName: "Euro", countryName: "France or European Union" },
  FJD: { flagCode: "FJ", currencyName: "Fiji Dollar", countryName: "Fiji" },
  FKP: { flagCode: "FK", currencyName: "Falkland Islands Pound", countryName: "Falkland Islands" },
  GBP: { flagCode: "GB", currencyName: "Pound Sterling", countryName: "United Kingdom" },
  GEL: { flagCode: "GE", currencyName: "Georgian Lari", countryName: "Georgia" },
  GGP: { flagCode: "GG", currencyName: "Guernsey Pound", countryName: "Guernsey" },
  GHS: { flagCode: "GH", currencyName: "Ghanaian Cedi", countryName: "Ghana" },
  GIP: { flagCode: "GI", currencyName: "Gibraltar Pound", countryName: "Gibraltar" },
  GMD: { flagCode: "GM", currencyName: "Gambian Dalasi", countryName: "Gambia" },
  GNF: { flagCode: "GN", currencyName: "Guinean Franc", countryName: "Guinea" },
  GTQ: { flagCode: "GT", currencyName: "Guatemalan Quetzal", countryName: "Guatemala" },
  GYD: { flagCode: "GY", currencyName: "Guyanese Dollar", countryName: "Guyana" },
  HKD: { flagCode: "HK", currencyName: "Hong Kong Dollar", countryName: "Hong Kong" },
  HNL: { flagCode: "HN", currencyName: "Honduran Lempira", countryName: "Honduras" },
  HRK: { flagCode: "HR", currencyName: "Croatian Kuna", countryName: "Croatia" },
  HTG: { flagCode: "HT", currencyName: "Haitian Gourde", countryName: "Haiti" },
  HUF: { flagCode: "HU", currencyName: "Hungarian Forint", countryName: "Hungary" },
  IDR: { flagCode: "ID", currencyName: "Indonesian Rupiah", countryName: "Indonesia" },
  ILS: { flagCode: "IL", currencyName: "Israeli New Shekel", countryName: "Israel" },
  INR: { flagCode: "IN", currencyName: "Indian Rupee", countryName: "India" },
  IQD: { flagCode: "IQ", currencyName: "Iraqi Dinar", countryName: "Iraq" },
  IRR: { flagCode: "IR", currencyName: "Iranian Rial", countryName: "Iran" },
  ISK: { flagCode: "IS", currencyName: "Icelandic Króna", countryName: "Iceland" },
  JMD: { flagCode: "JM", currencyName: "Jamaican Dollar", countryName: "Jamaica" },
  JOD: { flagCode: "JO", currencyName: "Jordanian Dinar", countryName: "Jordan" },
  JPY: { flagCode: "JP", currencyName: "Japanese Yen", countryName: "Japan" },
  KES: { flagCode: "KE", currencyName: "Kenyan Shilling", countryName: "Kenya" },
  KGS: { flagCode: "KG", currencyName: "Kyrgyzstani Som", countryName: "Kyrgyzstan" },
  KHR: { flagCode: "KH", currencyName: "Cambodian Riel", countryName: "Cambodia" },
  KMF: { flagCode: "KM", currencyName: "Comorian Franc", countryName: "Comoros" },
  KPW: { flagCode: "KP", currencyName: "North Korean Won", countryName: "North Korea" },
  KRW: { flagCode: "KR", currencyName: "South Korean Won", countryName: "South Korea" },
  KWD: { flagCode: "KW", currencyName: "Kuwaiti Dinar", countryName: "Kuwait" },
  KYD: { flagCode: "KY", currencyName: "Cayman Islands Dollar", countryName: "Cayman Islands" },
  KZT: { flagCode: "KZ", currencyName: "Kazakhstani Tenge", countryName: "Kazakhstan" },
  LAK: { flagCode: "LA", currencyName: "Lao Kip", countryName: "Laos" },
  LBP: { flagCode: "LB", currencyName: "Lebanese Pound", countryName: "Lebanon" },
  LKR: { flagCode: "LK", currencyName: "Sri Lanka Rupee", countryName: "Sri Lanka" },
  LRD: { flagCode: "LR", currencyName: "Liberian Dollar", countryName: "Liberia" },
  LSL: { flagCode: "LS", currencyName: "Lesotho Loti", countryName: "Lesotho" },
  LTL: { flagCode: "LT", currencyName: "Lithuanian Litas", countryName: "Lithuania" },
  LVL: { flagCode: "LV", currencyName: "Latvian Lats", countryName: "Latvia" },
  LYD: { flagCode: "LY", currencyName: "Libyan Dinar", countryName: "Libya" },
  MAD: { flagCode: "MA", currencyName: "Moroccan Dirham", countryName: "Morocco" },
  MDL: { flagCode: "MD", currencyName: "Moldovan Leu", countryName: "Moldova" },
  MGA: { flagCode: "MG", currencyName: "Malagasy Ariary", countryName: "Madagascar" },
  MKD: { flagCode: "MK", currencyName: "Macedonian Denar", countryName: "North Macedonia" },
  MMK: { flagCode: "MM", currencyName: "Burmese Kyat", countryName: "Myanmar" },
  MNT: { flagCode: "MN", currencyName: "Mongolian Tögrög", countryName: "Mongolia" },
  MOP: { flagCode: "MO", currencyName: "Macanese Pataca", countryName: "Macau" },
  MRO: { flagCode: "MR", currencyName: "Mauritanian Ouguiya", countryName: "Mauritania" },
  MTL: { flagCode: "MT", currencyName: "Maltese Lira", countryName: "Malta" },
  MUR: { flagCode: "MU", currencyName: "Mauritian Rupee", countryName: "Mauritius" },
  MVR: { flagCode: "MV", currencyName: "Maldivian Rufiyaa", countryName: "Maldives" },
  MWK: { flagCode: "MW", currencyName: "Malawian Kwacha", countryName: "Malawi" },
  MXN: { flagCode: "MX", currencyName: "Mexican Peso", countryName: "Mexico" },
  MYR: { flagCode: "MY", currencyName: "Malaysian Ringgit", countryName: "Malaysia" },
  MZN: { flagCode: "MZ", currencyName: "Mozambican Metical", countryName: "Mozambique" },
  NAD: { flagCode: "NA", currencyName: "Namibian Dollar", countryName: "Namibia" },
  XPF: { flagCode: "NC", currencyName: "CFP Franc", countryName: "New Caledonia" },
  NGN: { flagCode: "NG", currencyName: "Nigerian Naira", countryName: "Nigeria" },
  NIO: { flagCode: "NI", currencyName: "Nicaraguan Córdoba", countryName: "Nicaragua" },
  NPR: { flagCode: "NP", currencyName: "Nepalese Rupee", countryName: "Nepal" },
  NZD: { flagCode: "NZ", currencyName: "New Zealand Dollar", countryName: "New Zealand" },
  OMR: { flagCode: "OM", currencyName: "Omani Rial", countryName: "Oman" },
  PAB: { flagCode: "PA", currencyName: "Panamanian Balboa", countryName: "Panama" },
  PEN: { flagCode: "PE", currencyName: "Peruvian Sol", countryName: "Peru" },
  PGK: { flagCode: "PG", currencyName: "Papua New Guinean Kina", countryName: "Papua New Guinea" },
  PHP: { flagCode: "PH", currencyName: "Philippine Peso", countryName: "Philippines" },
  PKR: { flagCode: "PK", currencyName: "Pakistani Rupee", countryName: "Pakistan" },
  PLN: { flagCode: "PL", currencyName: "Polish Złoty", countryName: "Poland" },
  PYG: { flagCode: "PY", currencyName: "Paraguayan Guaraní", countryName: "Paraguay" },
  QAR: { flagCode: "QA", currencyName: "Qatari Riyal", countryName: "Qatar" },
  RON: { flagCode: "RO", currencyName: "Romanian Leu", countryName: "Romania" },
  RSD: { flagCode: "RS", currencyName: "Serbian Dinar", countryName: "Serbia" },
  RUB: { flagCode: "RU", currencyName: "Russian Ruble", countryName: "Russia" },
  RWF: { flagCode: "RW", currencyName: "Rwandan Franc", countryName: "Rwanda" },
  SAR: { flagCode: "SA", currencyName: "Saudi Riyal", countryName: "Saudi Arabia" },
  SBD: { flagCode: "SB", currencyName: "Solomon Islands Dollar", countryName: "Solomon Islands" },
  SCR: { flagCode: "SC", currencyName: "Seychellois Rupee", countryName: "Seychelles" },
  SDG: { flagCode: "SD", currencyName: "Sudanese Pound", countryName: "Sudan" },
  SEK: { flagCode: "SE", currencyName: "Swedish Krona", countryName: "Sweden" },
  SGD: { flagCode: "SG", currencyName: "Singapore Dollar", countryName: "Singapore" },
  SKK: { flagCode: "SK", currencyName: "Slovak Koruna", countryName: "Slovakia" },
  SLL: { flagCode: "SL", currencyName: "Sierra Leonean Leone", countryName: "Sierra Leone" },
  SOS: { flagCode: "SO", currencyName: "Somali Shilling", countryName: "Somalia" },
  SRD: { flagCode: "SR", currencyName: "Surinamese Dollar", countryName: "Suriname" },
  STN: { flagCode: "ST", currencyName: "São Tomé and Príncipe Dobra", countryName: "São Tomé and Príncipe" },
  SVC: { flagCode: "SV", currencyName: "Salvadoran colón", countryName: "El Salvador" },
  SYP: { flagCode: "SY", currencyName: "Syrian Pound", countryName: "Syria" },
  SZL: { flagCode: "SZ", currencyName: "Eswatini Lilangeni", countryName: "Eswatini" },
  THB: { flagCode: "TH", currencyName: "Thai Baht", countryName: "Thailand" },
  TJS: { flagCode: "TJ", currencyName: "Tajikistani Somoni", countryName: "Tajikistan" },
  TMT: { flagCode: "TM", currencyName: "Turkmenistan Manat", countryName: "Turkmenistan" },
  TND: { flagCode: "TN", currencyName: "Tunisian Dinar", countryName: "Tunisia" },
  TOP: { flagCode: "TO", currencyName: "Tongan Paʻanga", countryName: "Tonga" },
  TRY: { flagCode: "TR", currencyName: "Turkish Lira", countryName: "Turkey" },
  TTD: { flagCode: "TT", currencyName: "Trinidad and Tobago Dollar", countryName: "Trinidad and Tobago" },
  TWD: { flagCode: "TW", currencyName: "New Taiwan Dollar", countryName: "Taiwan" },
  TZS: { flagCode: "TZ", currencyName: "Tanzanian Shilling", countryName: "Tanzania" },
  UAH: { flagCode: "UA", currencyName: "Ukrainian Hryvnia", countryName: "Ukraine" },
  UGX: { flagCode: "UG", currencyName: "Ugandan Shilling", countryName: "Uganda" },
  USD: { flagCode: "US", currencyName: "United States Dollar", countryName: "United States" },
  UYU: { flagCode: "UY", currencyName: "Uruguayan Peso", countryName: "Uruguay" },
  UZS: { flagCode: "UZ", currencyName: "Uzbekistani So'm", countryName: "Uzbekistan" },
  VES: { flagCode: "VE", currencyName: "Venezuelan Bolívar Soberano", countryName: "Venezuela" },
  VND: { flagCode: "VN", currencyName: "Vietnamese Đồng", countryName: "Vietnam" },
  VUV: { flagCode: "VU", currencyName: "Vanuatu Vatu", countryName: "Vanuatu" },
  YER: { flagCode: "YE", currencyName: "Yemeni Rial", countryName: "Yemen" },
  ZAR: { flagCode: "ZA", currencyName: "South African Rand", countryName: "South Africa" },
  ZMK: { flagCode: "ZM", currencyName: "Zambian Kwacha", countryName: "Zambia" },
  ZWL: { flagCode: "ZW", currencyName: "Zimbabwean Dollar", countryName: "Zimbabwe" }
};
